#!/bin/bash

cd /homes/tparker/data/src/comicsgrab
python grabber.py -g palfrey output 2>&1 > /tmp/comicsgrab.log
if [ $? -ne 0 ] ; then
	mail -s "Comicsgrab" tparker@doc.ic.ac.uk < /tmp/comicsgrab.log
fi

exit 0

