# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 22:29
from __future__ import unicode_literals

import comicsgrab.django.protobuffield
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('pb', comicsgrab.django.protobuffield.ProtobufField()),
            ],
            options={
                'db_table': 'comics_classes',
            },
        ),
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('homepage', models.CharField(max_length=200)),
                ('pb', comicsgrab.django.protobuffield.ProtobufField()),
            ],
            options={
                'db_table': 'comics_strips',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pb', comicsgrab.django.protobuffield.ProtobufField()),
            ],
            options={
                'db_table': 'comics_users',
            },
        ),
    ]
